on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

name: release-please

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: google-github-actions/release-please-action@v3.7.11
              id: release
              with:
                  release-type: node
                  token: ${{secrets.GITHUB_TOKEN}}
                  command: manifest

            # Adiciona o arquivo System.json as releases do sistema.
            - name: Upload Release Artifact
              if: ${{ steps.release.outputs.release_created }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: gh release upload ${{ steps.release.outputs.tag_name }} ./system.json
